#Created by webjeda - http://webjeda.com

# Site settings
title: "Tangan Dewa"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: your-email@domain.com
description: Kumpulan Info Agen Judi Online Terpercaya dan Resmi di Indonesia.
baseurl: "https://mosiz.github.io/gemarbola"
url: "https://mosiz.github.io/gemarbola"

permalink: :title/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: /page:num/


# Tracker
analytics: 

# Comments
disqus-shortname: 

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate]
