#Created by webjeda - http://webjeda.com

# Site settings
title: "Gemar Bola"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: your-email@domain.com
description: Berisikan info tempat taruhan judi bola di bandar situs agen bola online terbesar terlengkap resmi dan terpercaya di Indonesia.
baseurl: ""
url: "https://mosiz.github.io/gemarbola/"

permalink: :title/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: /page:num/


# Tracker
analytics: 

# Comments
disqus-shortname: 

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]
