#Created by webjeda - http://webjeda.com

# Site settings
title: "Gemar Bola Online"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: your-email@domain.com
description: Berisikan info seputar situs agen bola, bandar bola, taruhan bola, judi bola online terbesar terlengkap dan terpercaya di Indonesia.
baseurl: "/gemarbola"
url: "https://mosiz.github.io/gemarbola"

permalink: :title/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: /page:num/


# Tracker
analytics: 

# Comments
disqus-shortname: 

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate]

sitemap:
  lastmod: 2014-01-23
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'
